name: CI

on:
  # Will run on all PR's and pushes to main
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2       
        with:
          python-version: 3.10.12

      - name: Install SCons
        run: python -m pip install scons

      - name: Running environment setup
        run: scons setup

      - name: Running lint check
        run: scons lint
